config/routes.rb
Planto::Application.routes.draw do
  resources :links do
    resources :link_stats
  end

  root :to => 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base

  require 'rest_client'

  has_one :link_stat, :dependent => :destroy

  attr_accessible :url

  before_create :create_stats

  def name
  	"http://api.facebook.com/restserver.php?method=links.getStats&urls=#{url}"
  end

  def create_stats
  	stats = Hash.from_xml(RestClient.get(name, {:accept => :xml}))['links_getStats_response']
    [:url, :normalized_url, :total_count, 
     :click_count, :comments_fbid, :commentsbox_count].each{|key| stats['link_stat'].delete(key.to_s)}
  	self.build_link_stat(stats['link_stat'])  	
  end
end

app/models/link_stat.rb
class LinkStat < ActiveRecord::Base
  belongs_to :link
  attr_accessible :comment_count, :like_count, :link_is, :share_count
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/link_stats_controller.rb
class LinkStatsController < ApplicationController
  # GET /link_stats
  # GET /link_stats.json
  def index
    @link = Link.find_by_id(params[:link_id])
    @link_stat = @link.link_stat

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @link_stat }
    end
  end

  def update
    @link = Link.find_by_id(params[:link_id])
    @link_stat = @link.create_stats
    # @link_stat = LinkStat.find(params[:id])

    respond_to do |format|
      if @link_stat.update_attributes(params[:link_stat])
        format.html { redirect_to link_link_stats_path(@link.id) , notice: 'Link stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link_stat.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_path, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_stats_helper.rb
module LinkStatsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/link_stats/index.html.erb
<h1>Listing link_stats</h1>

<table>
  <tr>
    <th>Link id</th>
    <th>Like count</th>
    <th>Share count</th>
    <th>Comment count</th>
    <th></th>
    
  </tr>


  <tr>
    <td><%= @link_stat.link.url %></td>
    <td><%= @link_stat.like_count %></td>
    <td><%= @link_stat.share_count %></td>
    <td><%= @link_stat.comment_count %></td>
    <td><%= link_to 'Update', link_link_stat_path(@link,@link_stat) , :method => :put%></td>
    
  </tr>

</table>

<br />

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Name</th>
    
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.name %></td>
    <td><%= link_to 'Show', link_link_stats_path(link.id) %></td>
    
    <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>